### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Lectric1** [jonzenor/ChristianGuilds#127]
![favIcon](https://user-images.githubusercontent.com/54757398/90360120-c1070d80-e028-11ea-86c3-46aaa146647b.png)
![Icon](https://user-images.githubusercontent.com/54757398/90360123-c19fa400-e028-11ea-8102-e6ccf927d5f5.png)
Logo Ideas

**Comment by jonzenor** [comment]
I really like these logo ideas... thanks so much for putting in the time for them. Can't wait to see what the final product looks like!
