### ISSUE TITLE
Verify permission check on role remove confirmation page

### ISSUE THREAD

**Issue by Lectric1** [jonzenor/ChristianGuilds#156]
![image](https://user-images.githubusercontent.com/54757398/90978575-e7431680-e51c-11ea-8e71-e5b517b9849f.png)

**Comment by Lectric1** [comment]
found some more info, it appears to be a leftover if you had a role to begin with, possible permissions are not removed with the rank?

**Comment by jonzenor** [comment]
Probably a caching issue. Thanks.

Related to #162
