### ISSUE TITLE
Update menu needs a name fix (games)

### ISSUE THREAD

**Issue by Lectric1** [jonzenor/ChristianGuilds#157]
![image](https://user-images.githubusercontent.com/54757398/90978711-cd560380-e51d-11ea-93c3-f6abd881149d.png)

**Comment by jonzenor** [comment]
Thank you for submitting this. In this instance I can tell from the context, however in the future please post a link to the page you are in where you see the error.

**Comment by Lectric1** [comment]
will do :D
