### ISSUE TITLE
admins dont change names

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#166]
![image](https://user-images.githubusercontent.com/54007781/90988836-386dfd00-e553-11ea-80d5-351928e2ae37.png)
![image](https://user-images.githubusercontent.com/54007781/90988870-6eab7c80-e553-11ea-83f2-684de5ab39fe.png)
https://forge.christianguilds.com/profile/1/edit The admin name changes dont actually go though but if you do the same thing with a non-admin the name does go though

**Comment by Planet-math** [comment]
it does work after a bit though

**Comment by jonzenor** [comment]
This is a cache issue of some kind... Make sure that the recent items list in the ACP panel gets its cache cleared.
