### ISSUE TITLE
[BUG] permissions no longer work

### ISSUE THREAD

**Issue by Lectric1** [jonzenor/ChristianGuilds#174]
**Describe the bug** :boom:
Permissions don't do anything.

**To Reproduce** :dizzy:
1. Go to https://forge.christianguilds.com/forgePowerUp
2. 

**Expected behavior** :exclamation:
Expected to see the menu to look at the games and other users

**Screenshots** 
![Screenshot_20200825-134538](https://user-images.githubusercontent.com/54757398/91209641-08049b00-e6da-11ea-97d0-f5ed542ac5a5.png)

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: Android 8.1
 - Browser: chrome
 
**Additional context** :space_invader:

**Comment by jonzenor** [comment]
You have to click on the red Grant Admin Permissions button first. :D

**Comment by Lectric1** [comment]
I clicked all 3

**Comment by jonzenor** [comment]
You didn't list that in your list of steps to reproduce the error.... 😝

**Comment by Lectric1** [comment]
Lol it was rushed between classes

**Comment by Lectric1** [comment]
It works now gonna close ticket
