### ISSUE TITLE
[BUG] no home page

### ISSUE THREAD

**Issue by Lectric1** [jonzenor/ChristianGuilds#177]
**Describe the bug** :boom:
When logging in it sends you to a nonexistent home page and you end up with a good old fashioned 404 error

**To Reproduce** :dizzy:
1. https://forge.christianguilds.com/home

**Expected behavior** :exclamation:
I expected to see the home page.

**Screenshots** :sunrise_over_mountains:
![Screenshot_20200826-063736](https://user-images.githubusercontent.com/54757398/91294102-046b2580-e767-11ea-8a21-b98648462682.png)

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: Android 8.1
 - Browser: chrome
 
**Additional context** :space_invader:
Tried without logging in to it as well.

**Comment by Planet-math** [comment]
im having the same problem

**Comment by Planet-math** [comment]
if you are loged out you can still acces the home page
