### ISSUE TITLE
the guild stopwatch always stays at 1 second

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#179]
**Describe the bug** :boom:
if you create a guild and the cheack out the guild it always says one second for when it was created
**To Reproduce** :dizzy:
1. Go to 'https://forge.christianguilds.com/guilds'

**Expected behavior** :exclamation: The  guilds in the photo were created ~10 minutes ago so it should say 10 minutes not 1 second

 The  guilds in the photo were created ~10 minutes ago but it is stuck at 1 second**Screenshots** :sunrise_over_mountains:
![image](https://user-images.githubusercontent.com/54007781/91326201-4903ba80-e781-11ea-87b0-5e7246647a7d.png)

**Desktop (please complete the following information):** :iphone: :computer:
 
**Additional context** :space_invader:

**Comment by Planet-math** [comment]
and irefreshed the page and stuff

**Comment by jonzenor** [comment]
Hahaha, leave it to you to want a stop watch. :D 

Good catch... it's a cache issue, however I don't think being a counter should be a feature we strive for. So, I think I should make this just say "Today"
