### ISSUE TITLE
[BUG] edit guild feature. 

### ISSUE THREAD

**Issue by Lectric1** [jonzenor/ChristianGuilds#181]
**Describe the bug** :boom:
When in guild list, edit guild button does not work. It simply reloads the page

**To Reproduce** :dizzy:
1. Go to https://forge.christianguilds.com/guilds
2. Click on the edit guild button
3. See error

**Expected behavior** :exclamation:
The ability to change names of a guild

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: Android 8.1
 - Browser chrome
 
**Additional context** :space_invader:
I have admin permissions

**Comment by Planet-math** [comment]
Final told me not to make a bug on that because he just didnt have the time po put in the funcinality

**Comment by Lectric1** [comment]
Well close then

**Comment by jonzenor** [comment]
Good catch, but yeah... I should not leave black links in the system if I don't want you guys to test it yet :D

My failure, sorry snotty that. Good work guys!
