### ISSUE TITLE
The second box for improving games is wrong

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#188]
**Describe the bug** :boom:
if you have a guild that has a diffrent game and a game master goes to the aproving game pages the second genre dropdown contains games.
**To Reproduce** :dizzy:
1. Create guild with a game not in the database
2. become a game master
3. Go to 'https://forge.christianguilds.com/acp/games/pending'

**Expected behavior** :exclamation: I expected the genre dropdown would show genres or that the genre was renamed to games

**Screenshots** :sunrise_over_mountains:

![image](https://user-images.githubusercontent.com/54007781/91579147-6b741000-e908-11ea-98d8-7b3630b0f874.png)

**Desktop (please complete the following information):** :iphone: :computer:
 
**Additional context** :space_invader:

**Comment by jonzenor** [comment]
Good catch. The language variable in the view file just needs to be updated to say Game instead of Genre.
