### ISSUE TITLE
button to approve pending game is slightly wrong

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#193]
**URL To See Incorrect Text** :musical_score:
https://forge.christianguilds.com/acp/games/pending (first create guild with no genre)

**Wrong Text** :boom:
butoon to add genre says "update genre"
**Correct Text** :star2:
What should it say?
somthing like "add genre" or "update guild"
**Screenshots** :sunset:
For extra context, feel free to share a screen shot
![image](https://user-images.githubusercontent.com/54007781/91643272-eb74a580-e9ee-11ea-86d4-e7276fdbdf4d.png)

**Comment by jonzenor** [comment]
Maybe something like "Set Game's Genre" would be more generic and appropriate in either case that involves this button. Or should I say... butoon.....
