### ISSUE TITLE
you can search as an logged out person

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#233]
**Describe the bug** :boom:
as a logged out person i can seach secsefully and even view guilds and view users
**To Reproduce** :dizzy:
1. be logged out
2.searchg somthing
3. click on a guild or anything

**Expected behavior** :exclamation:
i would get kicked to the login page like with anything else.
**Screenshots** :sunrise_over_mountains:
![image](https://user-images.githubusercontent.com/54007781/92336528-fec2e900-f05e-11ea-8081-87133e21645f.png)

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: windos 10
 - Browser chrome, safari
 
**Additional context** :space_invader:
some pages do still kick you back to the begging

**Comment by jonzenor** [comment]
Not a bug. Guests should be able to view public pages, but not any sensitive information.
