### ISSUE TITLE
communitys dont regester in acp

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#251]
**Describe the bug** :boom:
if you make a community it doesnt show up in the ACP

**To Reproduce** :dizzy:
1. make a community
2. go to acp
3. See error

**Expected behavior** :exclamation:
it would show up after i added it

**Screenshots** :sunrise_over_mountains:
![image](https://user-images.githubusercontent.com/54007781/93157091-c5295800-f6c6-11ea-8ca4-0756f3f8f13b.png)

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: windos 10
 - Browser chrome
 
**Additional context** :space_invader:
it works with guilds

**Comment by jonzenor** [comment]
Pretty sure this is a caching issue.
