### ISSUE TITLE
putting nothing in relms causes sql error

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#255]
**Describe the bug** :boom:
when adding

**To Reproduce** :dizzy:
1. Go to 'a game'
2. manage relms
3.add a relm
4. put stuff in the name but nothing in the type
5. See error

**Expected behavior** :exclamation:
it would say somthing like this can not be shorter then 1 letter or somthong

**Screenshots** :sunrise_over_mountains:
![image](https://user-images.githubusercontent.com/54007781/93159233-04f23e80-f6cb-11ea-9cba-6f13cae3844e.png)
![image](https://user-images.githubusercontent.com/54007781/93159245-0de31000-f6cb-11ea-846d-10140c35dcb4.png)

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: windos 10
 - Browser chrome
 
**Additional context** :space_invader:

**Comment by jonzenor** [comment]
Need to verify validation on that page.
