### ISSUE TITLE
after creating a community the page says the wrong thing

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#263]
**URL To See Incorrect Text** :musical_score:
https://forge.christianguilds.com/community/1(after creating community)

**Wrong Text** :boom:
The part that shows leaders says "guild leaders"

**Correct Text** :star2:
It should say community leaders
**Screenshots** :sunset:
For extra context, feel free to share a screen shot
![image](https://user-images.githubusercontent.com/54007781/93655970-1ea1c780-f9e4-11ea-86b0-fe9f90254881.png)

**Comment by jonzenor** [comment]
I must have fixed it in a previous change because I could not replicate this issue.
