### ISSUE TITLE
 You cant remove description from Communities

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#271]
**Describe the bug** :boom:
IF you go to a community it doesn't let you remove the description

**To Reproduce** :dizzy:
1. Go create or go to your community
2. put no description (or don't add one)
3. See error

**Expected behavior** :exclamation:
I expeted i would be able to have no descripton like with gulds

**Screenshots** :sunrise_over_mountains:
![image](https://user-images.githubusercontent.com/54007781/93963697-2088c500-fd1b-11ea-8140-7041785c9d06.png)

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: windows 10
 - Browser chrome 

**Additional context** :space_invader:
This might not be a bug

**Comment by jonzenor** [comment]
Description should be a requirement. There is not reason for just a name with absolutely no description for the guild/community, that I can think of.
