### ISSUE TITLE
IF you put a super long description in to your guild/community it is too much

### ISSUE THREAD

**Issue by Planet-math** [jonzenor/ChristianGuilds#278]
**Describe the bug** :boom:
if you nearly max out your guild description it takes up too much of the screen and the text is too close together
**To Reproduce** :dizzy:
1. Go make a guild/community
2. Make description super long
3. Go to guild/community over view

**Expected behavior** :exclamation:
It would truncate the description or make it a little easier to read
**Screenshots** :sunrise_over_mountains:
![image](https://user-images.githubusercontent.com/54007781/94356137-37475880-0048-11eb-8a32-7b4d662c6732.png)
![image](https://user-images.githubusercontent.com/54007781/94356207-d9ffd700-0048-11eb-9760-4d3106e4069c.png)

**Desktop (please complete the following information):** :iphone: :computer:
 - OS: windos 10
 - Browser chrome
 
**Additional context** :space_invader:
The issue is pretty much anywhere
![image](https://user-images.githubusercontent.com/54007781/94356296-08ca7d00-004a-11eb-8fb4-61c542c3d418.png)

**Comment by jonzenor** [comment]
Ho much information the guild master wants to display is up to them. Also, I fixed the edit guild button covering the description issue tonight.
